import sys
from TFM_LIB import *

DATOS=IMPORTACION_DATOS_GOOGLE_CLOUD()
EQUIPOS=LISTADO_NUMERICO_EQUIPOS(DATOS)
DATOS_LIMPIOS=LIMPIEZA_DATOS_EQUIPOS_NUMERICOS(DATOS,EQUIPOS)
ELO=CALCULO_RANKING_ELO(DATOS_LIMPIOS,EQUIPOS)
HISTORICO,CURRENT,df_team_elos=ELO
CARGAR_ELO_HISTORICO(df_team_elos)
PREDICCION=CLASSIFICATION_MODELS(DATOS_LIMPIOS)
CARGAR_RESULTADO_MIERDA(PREDICCION)

DATOS=IMPORTACION_DATOS_GOOGLE_CLOUD_XG(INDIVIDUAL=True)
SHOTSXG=REGRESSION_MODELS('shotsXG',DATOS)
CARGAR_RESULTADO_MIERDA_XG_INDIVIDUAL(SHOTSXG,'shotsXG')
NONSHOTSXG=REGRESSION_MODELS('non_shotsXG',DATOS)
CARGAR_RESULTADO_MIERDA_XG_INDIVIDUAL(NONSHOTSXG,'non_shotsXG')

HISTORICOS=QUERY_PARTICULAR(HISTORICO=True,TEMPORADA='2019-20')
ACTUAL=QUERY_PARTICULAR(HISTORICO=False,TEMPORADA='2019-20')
SXG=LOCURA(HISTORICOS,ACTUAL,'shotsXG')
CARGAR_XG_JUEGOS(SXG,'shotsXG')
NXG=LOCURA(HISTORICOS,ACTUAL,'non_shotsXG')
CARGAR_XG_JUEGOS(NXG,'non_shotsXG')